kind: pipeline
type: docker
name: default
steps:
  - name: build
    image: gradle:8.4
    volumes:
      - name: sdk
        path: /drone/src/sdk
      - name: gradle-cache
        path: /home/gradle/.gradle
    environment:
      ANDROID_HOME: /drone/src/sdk
    commands:
      - chmod +x gradlew
      - ./gradlew assembleRelease --stacktrace
  - name: upload
    image: minio/mc:RELEASE.2024-01-16T16-06-34Z
    environment:
      ADDRESS:
        from_secret: MINIO_ADDRESS
      ACCESS_KEY:
        from_secret: MINIO_ACCESS_KEY
      SECRET_KEY:
        from_secret: MINIO_SECRET_KEY
    commands:
      - mc config host add mio $ADDRESS $ACCESS_KEY $SECRET_KEY
      - mc cp CHANGES.md mio/uchi
      - mc cp app/build/outputs/apk/landscape/release/*.apk mio/uchi/apk/portrait
      - mc cp app/build/outputs/apk/portrait/release/*.apk mio/uchi/apk/landscape
volumes:
  - name: sdk
    host:
      path: /mnt/user/appdata/drone/tools/android/sdk
  - name: gradle-cache
    host:
      path: /mnt/user/appdata/drone/tools/gradle/cache-agmapp
